# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import EIHCameraAPI_pb2 as EIHCameraAPI__pb2
import EIHCamera_pb2 as EIHCamera__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in EIHCameraAPI_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EIHCameraApiStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.isCameraConnected = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/isCameraConnected',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.isCameraConnectedResponse.FromString,
                _registered_method=True)
        self.getIntrinsics = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getIntrinsics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getIntrinsicsResponse.FromString,
                _registered_method=True)
        self.getHandEyeParameters = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getHandEyeParameters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCamera__pb2.Camera.HandEyeParameters.FromString,
                _registered_method=True)
        self.getImageData = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getImageData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCamera__pb2.Camera.Image.Data.FromString,
                _registered_method=True)
        self.getImageConfiguration = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getImageConfiguration',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCamera__pb2.Camera.Image.Configuration.FromString,
                _registered_method=True)
        self.terminateCameraConnection = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/terminateCameraConnection',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.resumeCameraConnection = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/resumeCameraConnection',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getCapturingSettings = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getCapturingSettings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCamera__pb2.Camera.CapturingSettings.FromString,
                _registered_method=True)
        self.setCapturingSettings = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setCapturingSettings',
                request_serializer=EIHCameraAPI__pb2.setCapturingSettingsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getShutterTime = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getShutterTime',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getShutterTimeResponse.FromString,
                _registered_method=True)
        self.setShutterTime = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setShutterTime',
                request_serializer=EIHCameraAPI__pb2.setShutterTimeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getGain = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getGain',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getGainResponse.FromString,
                _registered_method=True)
        self.setGain = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setGain',
                request_serializer=EIHCameraAPI__pb2.setGainRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getWhiteBalance = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getWhiteBalance',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getWhiteBalanceResponse.FromString,
                _registered_method=True)
        self.setWhiteBalance = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setWhiteBalance',
                request_serializer=EIHCameraAPI__pb2.setWhiteBalanceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getFocus = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getFocus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getFocusResponse.FromString,
                _registered_method=True)
        self.setFocus = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setFocus',
                request_serializer=EIHCameraAPI__pb2.setFocusRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getImageSize = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/getImageSize',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=EIHCameraAPI__pb2.getImageSizeResponse.FromString,
                _registered_method=True)
        self.setImageSize = channel.unary_unary(
                '/TmEIHCamera.EIHCameraApi/setImageSize',
                request_serializer=EIHCameraAPI__pb2.setImageSizeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class EIHCameraApiServicer:
    """Missing associated documentation comment in .proto file."""

    def isCameraConnected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIntrinsics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getHandEyeParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminateCameraConnection(self, request, context):
        """Terminate or Resume TRI RobotCamera Connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resumeCameraConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCapturingSettings(self, request, context):
        """Get or Set all parameters of CapturingSettings 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setCapturingSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getShutterTime(self, request, context):
        """Get or Set the specific parameter of CapturingSettings 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setShutterTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setGain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWhiteBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setWhiteBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setFocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getImageSize(self, request, context):
        """Only two size:  1M = 1280*960,  5M = 2592*1944
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setImageSize(self, request, context):
        """Only two size:  1M = 1280*960,  5M = 2592*1944
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EIHCameraApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'isCameraConnected': grpc.unary_unary_rpc_method_handler(
                    servicer.isCameraConnected,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.isCameraConnectedResponse.SerializeToString,
            ),
            'getIntrinsics': grpc.unary_unary_rpc_method_handler(
                    servicer.getIntrinsics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getIntrinsicsResponse.SerializeToString,
            ),
            'getHandEyeParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.getHandEyeParameters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCamera__pb2.Camera.HandEyeParameters.SerializeToString,
            ),
            'getImageData': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCamera__pb2.Camera.Image.Data.SerializeToString,
            ),
            'getImageConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageConfiguration,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCamera__pb2.Camera.Image.Configuration.SerializeToString,
            ),
            'terminateCameraConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.terminateCameraConnection,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'resumeCameraConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.resumeCameraConnection,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getCapturingSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.getCapturingSettings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCamera__pb2.Camera.CapturingSettings.SerializeToString,
            ),
            'setCapturingSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.setCapturingSettings,
                    request_deserializer=EIHCameraAPI__pb2.setCapturingSettingsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getShutterTime': grpc.unary_unary_rpc_method_handler(
                    servicer.getShutterTime,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getShutterTimeResponse.SerializeToString,
            ),
            'setShutterTime': grpc.unary_unary_rpc_method_handler(
                    servicer.setShutterTime,
                    request_deserializer=EIHCameraAPI__pb2.setShutterTimeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getGain': grpc.unary_unary_rpc_method_handler(
                    servicer.getGain,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getGainResponse.SerializeToString,
            ),
            'setGain': grpc.unary_unary_rpc_method_handler(
                    servicer.setGain,
                    request_deserializer=EIHCameraAPI__pb2.setGainRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getWhiteBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getWhiteBalance,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getWhiteBalanceResponse.SerializeToString,
            ),
            'setWhiteBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.setWhiteBalance,
                    request_deserializer=EIHCameraAPI__pb2.setWhiteBalanceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getFocus': grpc.unary_unary_rpc_method_handler(
                    servicer.getFocus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getFocusResponse.SerializeToString,
            ),
            'setFocus': grpc.unary_unary_rpc_method_handler(
                    servicer.setFocus,
                    request_deserializer=EIHCameraAPI__pb2.setFocusRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getImageSize': grpc.unary_unary_rpc_method_handler(
                    servicer.getImageSize,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=EIHCameraAPI__pb2.getImageSizeResponse.SerializeToString,
            ),
            'setImageSize': grpc.unary_unary_rpc_method_handler(
                    servicer.setImageSize,
                    request_deserializer=EIHCameraAPI__pb2.setImageSizeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TmEIHCamera.EIHCameraApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TmEIHCamera.EIHCameraApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EIHCameraApi:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def isCameraConnected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/isCameraConnected',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.isCameraConnectedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getIntrinsics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getIntrinsics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getIntrinsicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getHandEyeParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getHandEyeParameters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCamera__pb2.Camera.HandEyeParameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getImageData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCamera__pb2.Camera.Image.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getImageConfiguration',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCamera__pb2.Camera.Image.Configuration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def terminateCameraConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/terminateCameraConnection',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def resumeCameraConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/resumeCameraConnection',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCapturingSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getCapturingSettings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCamera__pb2.Camera.CapturingSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setCapturingSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setCapturingSettings',
            EIHCameraAPI__pb2.setCapturingSettingsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getShutterTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getShutterTime',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getShutterTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setShutterTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setShutterTime',
            EIHCameraAPI__pb2.setShutterTimeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getGain',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getGainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setGain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setGain',
            EIHCameraAPI__pb2.setGainRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWhiteBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getWhiteBalance',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getWhiteBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setWhiteBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setWhiteBalance',
            EIHCameraAPI__pb2.setWhiteBalanceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getFocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getFocus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getFocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setFocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setFocus',
            EIHCameraAPI__pb2.setFocusRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getImageSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/getImageSize',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            EIHCameraAPI__pb2.getImageSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setImageSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TmEIHCamera.EIHCameraApi/setImageSize',
            EIHCameraAPI__pb2.setImageSizeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
